### ISSUE TITLE
The bot is not async

### ISSUE THREAD

**Issue by BLazzeD21** [BLazzeD21/Node.js-ChatGPT-Bot#4]
The bot does not work async, how can you either implement threads for different users or make it async?

The bot implements routers, but it's workaround:

**index.js:**

```javascript
import {startHandler} from './handlers/userHandlers.js';

bot.command('start', startHandler(sessions));
```
**handlers/userHandlers.js:**

```javascript
export const startHandler = (sessions) => {
  return async (ctx) => {
    const sessionId = ctx.message.chat.id;
    sessions[sessionId] = createInitialSession();
    await ctx.reply(LEXICON_EN['start'], menuKeyboard);
  };
};
```

**Comment by impuLssse** [comment]
что значит работает не асинхронно? напиши какое поведение получаешь и какое хочешь
что такое `sessions` и `LEXICON_EN`, `menuKeyboard`

**Comment by MKRhere** [comment]
The simple answer is just use webhook mode. In polling mode, the bot fetches up to 100 pending updates and waits for all of them to finish processing before fetching the next batch. In webhook mode, the bot receives one update per chat until you finish processing, regardless of how many chats there are.

**Comment by BLazzeD21** [comment]
LEXICON - это просто словарь со всеми репликами бота.
sessions - `сonst sessions = {};` из **index.js**
menuKeyboard - клавиатура с изображения

Обработчик с командой start приведен для примера того, как обрабатывается команда в боте. Проблема заключается в том, что при использовании команд бота, которые обращаются к openai API, он не может обрабатывать другие команды ни   от одного пользователя. Бот буквально зависает на одном пользователи и одном запросе.

![image](https://github.com/BLazzeD21/Node.js-ChatGPT-Bot/assets/48865829/b75c28a7-30d0-4bb9-af90-c70ee3e1d159)

**Comment by impuLssse** [comment]
> LEXICON - это просто словарь со всеми репликами бота. sessions - `сonst sessions = {};` из **index.js** menuKeyboard - клавиатура с изображения
> 
> Обработчик с командой start приведен для примера того, как обрабатывается команда в боте. Проблема заключается в том, что при использовании команд бота, которые обращаются к openai API, он не может обрабатывать другие команды ни от одного пользователя. Бот буквально зависает на одном пользователи и одном запросе.
> 
> ![image](https://user-images.githubusercontent.com/48865829/281732168-b75c28a7-30d0-4bb9-af90-c70ee3e1d159.png)

сделай замыкающую функцию внутри, которая будет не блочить твой поток (почитай что такое замыкания в Js)
либо есть еще 1 вариант, через `rxjs` сделать подписку на получение сообщение, и пока он обрабатывает твое сообщение, у тебя будет 1 текст, а когда придет ответ ты сможешь изменить сообщение на сообщение с ответом, либо отослать новое

**Comment by MKRhere** [comment]
If you need it to respond to the same chat even while processing, you just need to unhandle the promise that takes time. For example:

```TS
getLLMAnswer().then(async response => {
  await ctx.sendMessage(response);
}).catch(errorHandler);
```

You should not wait this. This method will cause three things you should be careful about:
1. Errors will no longer be caught by Telegraf because it's an unhandled promise. You should catch them yourself as shown above.
2. session will close while your unhandled promise is processing. You should not try to access or write to ctx.session in the `.then` callback.
3. Telegraf will no longer limit how many requests you're handling in these unhandled promises. You should use a ratelimit plugin if needed.

**Comment by BLazzeD21** [comment]
> If you need it to respond to the same chat even while processing, you just need to unhandle the promise that takes time. For example:
> 
> ```ts
> getLLMAnswer().then(async response => {
>   await ctx.sendMessage(response);
> }).catch(errorHandler);
> ```
> 
> You should not wait this. This method will cause three things you should be careful about:
> 
> 1. Errors will no longer be caught by Telegraf because it's an unhandled promise. You should catch them yourself as shown above.
> 2. session will close while your unhandled promise is processing. You should not try to access or write to ctx.session in the `.then` callback.
> 3. Telegraf will no longer limit how many requests you're handling in these unhandled promises. You should use a ratelimit plugin if needed.

I'm a little confused on how to apply this to my main handlers...

https://github.com/BLazzeD21/Node.js-ChatGPT-Bot/blob/master/src/handlers/openaiHandlers.js

**Comment by MKRhere** [comment]
For example:

```TS
openai.getImage(...).then(async image => {
  if (imageUrl == '400') {
  // ...test of the logic for this handler
}).catch(errorHandler);
```

Notice I'm not awaiting `openai.getImage`.

**Comment by BLazzeD21** [comment]
Thank you all very much for your help! The last solution worked!
